---
# install nfs-utils fails sometimes, when libnfsidmap is already installed in elder version
- name: Update libnfsidmap first
  package:
    name: libnfsidmap
    state: latest

- name: Install hypervisor packages
  package:
    name: {{ hypervisor_pkg }}
    state: latest

- name: Enable/start libvirt daemon
  service:
    name: libvirtd
    enabled: yes
    state: started
